get_property(_CMAKE_IN_TRY_COMPILE GLOBAL PROPERTY IN_TRY_COMPILE)
if(NOT _CMAKE_IN_TRY_COMPILE)
  if(NOT VCPKG_CRT_LINKAGE)
    include(${CMAKE_CURRENT_LIST_DIR}/../../triplets/${VCPKG_TARGET_TRIPLET}.cmake)
  endif()

  if(VCPKG_CRT_LINKAGE STREQUAL "dynamic")
    set(VCPKG_CRT_LINK_FLAG_PREFIX "/MD")
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
  elseif(VCPKG_CRT_LINKAGE STREQUAL "static")
    set(VCPKG_CRT_LINK_FLAG_PREFIX "/MT")
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
  else()
    message(FATAL_ERROR "Invalid setting for VCPKG_CRT_LINKAGE: \"${VCPKG_CRT_LINKAGE}\".")
  endif()

  set(CMAKE_CXX_STANDARD 20 CACHE STRING "")
  set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE STRING "")
  set(CMAKE_CXX_EXTENSIONS OFF CACHE STRING "")

  if(NOT VCPKG_CXX_FLAGS MATCHES "/EH")
    set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} /EHsc /d2FH4")
  endif()

  if(NOT VCPKG_CXX_FLAGS MATCHES "/GR")
    set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} /GR")
  endif()

  set(LLVM_ROOT "C:/Program Files/LLVM")

  set(CMAKE_C_COMPILER "${LLVM_ROOT}/bin/clang-cl.exe" CACHE STRING "")
  set(CMAKE_CXX_COMPILER "${LLVM_ROOT}/bin/clang-cl.exe" CACHE STRING "")
  set(CMAKE_RC_COMPILER "${LLVM_ROOT}/bin/llvm-rc.exe" CACHE STRING "")
  set(CMAKE_LINKER "link.exe" CACHE STRING "")

  set(MSVC_COMMON "/nologo /W3 /DWIN32 /D_WINDOWS /FC /Zc:inline /wd28251 /wd26451 /utf-8 /clang:-fcoroutines-ts /Z7")
  set(MSVC_COMMON_DEBUG "${VCPKG_CRT_LINK_FLAG_PREFIX}d /Ob0 /Od /RTC1 /GS /D_DEBUG")
  set(MSVC_COMMON_RELEASE "${VCPKG_CRT_LINK_FLAG_PREFIX} /Ox /Os /Oi /GF /Gy /GS- /DNDEBUG")

  set(CMAKE_C_FLAGS "${MSVC_COMMON} ${VCPKG_C_FLAGS}" CACHE STRING "")
  set(CMAKE_CXX_FLAGS "${MSVC_COMMON} /Zc:__cplusplus /permissive- ${VCPKG_CXX_FLAGS}" CACHE STRING "")

  set(CMAKE_C_FLAGS_DEBUG "${MSVC_COMMON_DEBUG} ${VCPKG_C_FLAGS_DEBUG}" CACHE STRING "")
  set(CMAKE_CXX_FLAGS_DEBUG "${MSVC_COMMON_DEBUG} ${VCPKG_CXX_FLAGS_DEBUG}" CACHE STRING "")

  set(CMAKE_C_FLAGS_RELEASE "${MSVC_COMMON_RELEASE} ${VCPKG_C_FLAGS_RELEASE}" CACHE STRING "")
  set(CMAKE_CXX_FLAGS_RELEASE "${MSVC_COMMON_RELEASE} ${VCPKG_CXX_FLAGS_RELEASE}" CACHE STRING "")

  set(CMAKE_STATIC_LINKER_FLAGS_DEBUG "" CACHE STRING "")
  set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "/DEBUG:FASTLINK /INCREMENTAL" CACHE STRING "")
  set(CMAKE_EXE_LINKER_FLAGS_DEBUG "/DEBUG:FASTLINK /INCREMENTAL" CACHE STRING "")

  set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "" CACHE STRING "")
  set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "/DEBUG:FULL /OPT:REF /OPT:ICF" CACHE STRING "")
  set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/DEBUG:FULL /OPT:REF /OPT:ICF" CACHE STRING "")

  set(CMAKE_STATIC_LINKER_FLAGS "/machine:X64" CACHE STRING "")
  set(CMAKE_SHARED_LINKER_FLAGS "/machine:X64 ${VCPKG_LINKER_FLAGS}" CACHE STRING "")
  set(CMAKE_EXE_LINKER_FLAGS "/machine:X64 ${VCPKG_LINKER_FLAGS}" CACHE STRING "")
endif()
