include_guard(GLOBAL)

get_property(_CMAKE_IN_TRY_COMPILE GLOBAL PROPERTY IN_TRY_COMPILE)
if(NOT _CMAKE_IN_TRY_COMPILE)
  set(CMAKE_C_STANDARD 11 CACHE STRING "")
  set(CMAKE_C_STANDARD_REQUIRED ON CACHE STRING "")
  set(CMAKE_C_EXTENSIONS OFF CACHE STRING "")

  set(CMAKE_CXX_STANDARD 20 CACHE STRING "")
  set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE STRING "")
  set(CMAKE_CXX_EXTENSIONS OFF CACHE STRING "")

  if(VCPKG_CRT_LINKAGE STREQUAL "dynamic")
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
    set(VCPKG_CRT_LINK_FLAG_PREFIX "/MD")
  elseif(VCPKG_CRT_LINKAGE STREQUAL "static")
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
    set(VCPKG_CRT_LINK_FLAG_PREFIX "/MT")
  else()
    message(FATAL_ERROR "Invalid setting for VCPKG_CRT_LINKAGE: \"${VCPKG_CRT_LINKAGE}\".")
  endif()

  set(CMAKE_C_FLAGS "/Zc:strictStrings /Zc:char8_t ${VCPKG_C_FLAGS} /utf-8" CACHE STRING "")
  set(CMAKE_CXX_FLAGS "/Zc:strictStrings /Zc:char8_t /Zc:__cplusplus /EHsc /d2FH4 /GR /permissive- ${VCPKG_CXX_FLAGS} /utf-8" CACHE STRING "")
  set(CMAKE_C_FLAGS_DEBUG "/Os /Oi /Ob2 /Gy /GS- /GF /Z7 ${VCPKG_C_FLAGS_DEBUG} ${VCPKG_CRT_LINK_FLAG_PREFIX}d" CACHE STRING "")
  set(CMAKE_CXX_FLAGS_DEBUG "/Os /Oi /Ob2 /Gy /GS- /GF /Z7 ${VCPKG_CXX_FLAGS_DEBUG} ${VCPKG_CRT_LINK_FLAG_PREFIX}d /await" CACHE STRING "")
  set(CMAKE_C_FLAGS_RELEASE "/Os /Oi /Oy /Ob2 /Gy /GS- /GF /GL /Z7 ${VCPKG_C_FLAGS_RELEASE} ${VCPKG_CRT_LINK_FLAG_PREFIX}" CACHE STRING "")
  set(CMAKE_CXX_FLAGS_RELEASE "/Os /Oi /Oy /Ob2 /Gy /GS- /GF /GL /Z7 ${VCPKG_CXX_FLAGS_RELEASE} ${VCPKG_CRT_LINK_FLAG_PREFIX} /await /await:heapelide" CACHE STRING "")

  set(CMAKE_STATIC_LINKER_FLAGS "/MACHINE:X64" CACHE STRING "")
  set(CMAKE_SHARED_LINKER_FLAGS "/MACHINE:X64 ${VCPKG_LINKER_FLAGS}" CACHE STRING "")
  set(CMAKE_EXE_LINKER_FLAGS "/MACHINE:X64 ${VCPKG_LINKER_FLAGS}" CACHE STRING "")

  set(CMAKE_STATIC_LINKER_FLAGS_DEBUG "" CACHE STRING "")
  set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "/DEBUG:FULL /OPT:REF /OPT:ICF" CACHE STRING "")
  set(CMAKE_EXE_LINKER_FLAGS_DEBUG "/DEBUG:FULL /OPT:REF /OPT:ICF" CACHE STRING "")

  set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "/LTCG" CACHE STRING "")
  set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")
  set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")

  set(CMAKE_RC_FLAGS "/nologo /c65001" CACHE STRING "")

  add_definitions(/DWIN32 /D_WINDOWS /D_WIN32_WINNT=0x0A00 /DWINVER=0x0A00)
endif()
