if(WIN32)
  if(NOT EXISTS ${CMAKE_CURRENT_LIST_DIR}/../../x64-windows-llvm.cmake)
    file(COPY ${CMAKE_CURRENT_LIST_DIR}/x64-windows-llvm.cmake DESTINATION ${CMAKE_CURRENT_LIST_DIR}/../..)
  endif()
  if(NOT EXISTS ${CMAKE_CURRENT_LIST_DIR}/../../x64-windows-msvc.cmake)
    file(COPY ${CMAKE_CURRENT_LIST_DIR}/x64-windows-msvc.cmake DESTINATION ${CMAKE_CURRENT_LIST_DIR}/../..)
  endif()
else()
  if(NOT EXISTS ${CMAKE_CURRENT_LIST_DIR}/../../x64-linux-llvm.cmake)
    file(COPY ${CMAKE_CURRENT_LIST_DIR}/x64-linux-llvm.cmake DESTINATION ${CMAKE_CURRENT_LIST_DIR}/../..)
  endif()
endif()
