if(WIN32)
  file(COPY ${CMAKE_CURRENT_LIST_DIR}/x64-windows-ipo.cmake DESTINATION ${CMAKE_CURRENT_LIST_DIR}/../..)
else()
  file(COPY ${CMAKE_CURRENT_LIST_DIR}/x64-linux-ipo.cmake DESTINATION ${CMAKE_CURRENT_LIST_DIR}/../..)
endif()
