if (NOT TBB_IMPORTED_TARGETS)
  set(TBB_IMPORTED_TARGETS "")
endif()

if (NOT TBB_FIND_COMPONENTS)
  set(TBB_FIND_COMPONENTS "tbb;tbbmalloc")
  foreach (_tbb_component ${TBB_FIND_COMPONENTS})
    set(TBB_FIND_REQUIRED_${_tbb_component} 1)
  endforeach()
endif()

set(TBB_INTERFACE_VERSION 11009)

foreach (_tbb_component ${TBB_FIND_COMPONENTS})
  set(TBB_${_tbb_component}_FOUND 0)
  set(_tbb_lib "${CMAKE_CURRENT_LIST_DIR}/../../lib${_tbb_component}.a")
  if (EXISTS "${_tbb_lib}")
    if (NOT TARGET TBB::${_tbb_component})
      add_library(TBB::${_tbb_component} STATIC IMPORTED)
      set_target_properties(TBB::${_tbb_component} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/../../../include")
      set_target_properties(TBB::${_tbb_component} PROPERTIES IMPORTED_LOCATION "${_tbb_lib}")
    else()
      message(STATUS "Using previously found TBB::${_tbb_component}")
    endif()
    list(APPEND TBB_IMPORTED_TARGETS TBB::${_tbb_component})
    set(TBB_${_tbb_component}_FOUND 1)
  elseif (TBB_FIND_REQUIRED AND TBB_FIND_REQUIRED_${_tbb_component})
    message(STATUS "Missing required Intel TBB component: ${_tbb_component}")
    set(TBB_FOUND FALSE)
  endif()
endforeach()

list(REMOVE_DUPLICATES TBB_IMPORTED_TARGETS)

unset(_tbb_lib)
