set(TBB_INTERFACE_VERSION 11009)

get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

add_library(TBB::tbb STATIC IMPORTED)
set_target_properties(TBB::tbb PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include")

add_library(TBB::malloc STATIC IMPORTED)
set_target_properties(TBB::malloc PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include")

if(WIN32)
  set_property(TARGET TBB::tbb APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
  set_target_properties(TBB::tbb PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/tbb_debug.lib")

  set_property(TARGET TBB::malloc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
  set_target_properties(TBB::malloc PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/tbbmalloc_debug.lib")

  set_property(TARGET TBB::tbb APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
  set_target_properties(TBB::tbb PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
    IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/tbb.lib")

  set_property(TARGET TBB::malloc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
  set_target_properties(TBB::malloc PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
    IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/tbbmalloc.lib")
else()
  set_target_properties(TBB::tbb PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
    IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/libtbb.a")

  set_target_properties(TBB::malloc PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
    IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/libtbbmalloc.a")
endif()

set(_IMPORT_PREFIX)
